### create order

POST http://localhost:5000/api/orders
Content-Type: application/json

{
    "order_details": [
        {
            "id": 1,
            "name": "Cornetto Pizza",
            "price": 19900,
            "qty": 1
        },
        {
            "id": 2,
            "name": "Barbeque Corn",
            "price": 21100,
            "qty": 1
        }
    ],
    "total": 62100
}


### get all orders

GET http://localhost:5000/api/orders