### create product
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "name": "Sprite Original",
    "price": 8000,
    "categories_id": 2
}


### get all products
GET http://localhost:5000/api/products
Content-Type: application/json


### search product
POST http://localhost:5000/api/products/search
Content-Type: application/json

{
    "query": "Pizza"
}